# Default values for bpdm-elastic.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  registry: docker.elastic.co
  repository: elasticsearch/elasticsearch
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

discoveryType: single-node

nameOverride: ""
fullnameOverride: ""


podSecurityContext:
  runAsNonRoot: true
  runAsUser: 10001
  runAsGroup: 3000
  fsGroup: 2000

securityContext:
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

resources:
  limits:
    cpu: 1000m
    memory: 8Gi
  requests:
    cpu: 500m
    memory: 4Gi